### ISSUE TITLE
Grey @ 2023-12-25 - intentional? GC shoulder buttons mapped to "small" L and R on only CC pro

### ISSUE THREAD

**Issue by NintendoManiac64** [libertyernie/Nintendont#12]
Just wondering if it's intentional that the grey build has the GC shoulder buttons mapped to the "small" L and R on *only* the CC pro.

**Comment by libertyernie** [comment]
Yeah, that's intentional - the idea behind the grey build is that every button maps to the GameCube button with the same name (so in-game instructions line up with what's on the controller), so the button labelled "L" will always map to L. On the CC it's the big one, and on the CC pro it's the small one.

**Comment by NintendoManiac64** [comment]
So as to match up with official non-homebrew Wii software and the like?

Otherwise I'm wondering if a sort of "cyan" build (or some other color between blue and grey) might be an idea where it's like the Navy build but strips out most of the per-game custom controls (maybe except for quality-of-life ones like the dpad, not needing to press R all the way, the "small L = Y" idea, etc)
